/**
 * THIS FILE IS GENERATED by uifork-vue.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork-vue promote ContactCard <version-id>
 */
import ContactCardV1 from "./ContactCard.v1.vue"
import ContactCardV2 from "./ContactCard.v2.vue"
import ContactCardV3 from "./ContactCard.v3.vue"
import ContactCardV4 from "./ContactCard.v4.vue"
import ContactCardV5 from "./ContactCard.v5.vue"

export const VERSIONS = {
  "v1": {
    render: ContactCardV1,
    label: "",
  },
  "v2": {
    render: ContactCardV2,
    label: "",
  },
  "v3": {
    render: ContactCardV3,
    label: "",
  },
  "v4": {
    render: ContactCardV4,
    label: "",
  },
  "v5": {
    render: ContactCardV5,
    label: "",
  },
}
