<script setup lang="ts">
/**
 * THIS FILE IS GENERATED by uifork-vue.
 * Do not edit this file directly. Edit the version files instead (e.g., ContactCard.v1.vue).
 * To stop versioning this component, run: npx uifork-vue promote ContactCard <version-id>
 */
import { ForkedComponent } from "uifork-vue"
import { VERSIONS } from "./ContactCard.versions"

defineOptions({ name: 'ContactCard' })
</script>

<template>
  <ForkedComponent
    id="ContactCard"
    :versions="VERSIONS"
    v-bind="$attrs"
  />
</template>
