/**
 * THIS FILE IS GENERATED by uifork-vue.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork-vue promote HomePage <version-id>
 */
import HomePageV1 from "./HomePage.v1.vue"
import HomePageV2 from "./HomePage.v2.vue"

export const VERSIONS = {
  "v1": {
    render: HomePageV1,
    label: "",
  },
  "v2": {
    render: HomePageV2,
    label: "",
  },
}
