"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., ContactCard.v1.tsx).
 * To stop versioning this component, run: npx uifork promote ContactCard <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./ContactCard.versions"

export default function ContactCard(props: any) {
  return (
    <ForkedComponent
      id="ContactCard"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
