"use client"

/**
 * THIS FILE IS GENERATED by uifork.
 * Do not edit this file directly. Edit the version files instead (e.g., FakeMessages.v1.tsx).
 * To stop versioning this component, run: npx uifork promote FakeMessages <version-id>
 */
import { ForkedComponent } from "uifork"
import { VERSIONS } from "./FakeMessages.versions"

export default function FakeMessages(props: any) {
  return (
    <ForkedComponent
      id="FakeMessages"
      versions={VERSIONS}
      props={props}
    />
  )
}

export { VERSIONS }
