/**
 * THIS FILE IS GENERATED by uifork.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork promote FakeMessages <version-id>
 */
import FakeMessagesV1 from "./FakeMessages.v1"
import FakeMessagesV2 from "./FakeMessages.v2"
import FakeMessagesV3 from "./FakeMessages.v3"
import FakeMessagesV4 from "./FakeMessages.v4"
import FakeMessagesV5 from "./FakeMessages.v5"
import FakeMessagesV6 from "./FakeMessages.v6"
import FakeMessagesV7 from "./FakeMessages.v7"
import FakeMessagesV8 from "./FakeMessages.v8"
import FakeMessagesV9 from "./FakeMessages.v9"
import FakeMessagesV10 from "./FakeMessages.v10"
export const VERSIONS = {
  "v1": {
    render: FakeMessagesV1,
    label: "",
  },
  "v2": {
    render: FakeMessagesV2,
    label: "",
  },
  "v3": {
    render: FakeMessagesV3,
    label: "",
  },
  "v4": {
    render: FakeMessagesV4,
    label: "",
  },
  "v5": {
    render: FakeMessagesV5,
    label: "",
  },
  "v6": {
    render: FakeMessagesV6,
    label: "",
  },
  "v7": {
    render: FakeMessagesV7,
    label: "",
  },
  "v8": {
    render: FakeMessagesV8,
    label: "",
  },
  "v9": {
    render: FakeMessagesV9,
    label: "",
  },
  "v10": {
    render: FakeMessagesV10,
    label: "",
  },
}
