const fs = require("fs");
const path = require("path");
const { VersionSync } = require("./watch");

class UISwitcherScaffold {
  constructor(filePath, shouldWatch = true) {
    this.shouldWatch = shouldWatch;
    this.originalFilePath = path.resolve(filePath);

    if (!fs.existsSync(this.originalFilePath)) {
      console.error(`File does not exist: ${this.originalFilePath}`);
      process.exit(1);
    }

    const parsedPath = path.parse(this.originalFilePath);
    this.componentName = parsedPath.name;
    this.parentDir = parsedPath.dir;
    this.originalExtension = parsedPath.ext; // .vue
    this.v1File = path.join(this.parentDir, `${this.componentName}.v1${this.originalExtension}`);
    this.versionsFile = path.join(this.parentDir, `${this.componentName}.versions.ts`);

    console.log(`Scaffolding forked component from: ${this.originalFilePath}`);
    console.log(`Component name: ${this.componentName}`);
    console.log(`Target directory: ${this.parentDir}`);
  }

  moveOriginalToV1() {
    // Move the original file to ComponentName.v1.vue in the same directory
    fs.renameSync(this.originalFilePath, this.v1File);
    console.log(`Moved: ${path.basename(this.originalFilePath)} → ${path.basename(this.v1File)}`);
  }

  createVersionsFile() {
    // Remove extension from import path
    const v1ImportPath = `./${this.componentName}.v1.vue`;
    const versionsContent = `/**
 * THIS FILE IS GENERATED by uifork-vue.
 * Manual edits to labels/descriptions are preserved, but structure changes may be overwritten.
 * To stop versioning this component, run: npx uifork-vue promote ${this.componentName} <version-id>
 */
import ${this.componentName}V1 from "${v1ImportPath}"

export const VERSIONS = {
  "v1": {
    render: ${this.componentName}V1,
    label: "",
  },
}
`;

    fs.writeFileSync(this.versionsFile, versionsContent);
    console.log(`Created: ${path.basename(this.versionsFile)}`);
  }

  createWrapper() {
    // Import ForkedComponent from uifork-vue package
    const versionsImportPath = `./${this.componentName}.versions`;
    const wrapperContent = `<script setup lang="ts">
/**
 * THIS FILE IS GENERATED by uifork-vue.
 * Do not edit this file directly. Edit the version files instead (e.g., ${this.componentName}.v1${this.originalExtension}).
 * To stop versioning this component, run: npx uifork-vue promote ${this.componentName} <version-id>
 */
import { ForkedComponent } from "uifork-vue"
import { VERSIONS } from "${versionsImportPath}"

defineOptions({ name: '${this.componentName}' })
</script>

<template>
  <ForkedComponent
    id="${this.componentName}"
    :versions="VERSIONS"
    v-bind="$attrs"
  />
</template>
`;

    const wrapperFile = path.join(this.parentDir, `${this.componentName}${this.originalExtension}`);
    fs.writeFileSync(wrapperFile, wrapperContent);
    console.log(`Created wrapper: ${path.basename(wrapperFile)}`);
  }

  scaffold() {
    this.moveOriginalToV1();
    this.createVersionsFile();
    this.createWrapper();

    console.log("\n✅ Scaffolding complete!");
    console.log("\nFor now, each version file must default-export its component.");
    console.log("\nNext steps:");
    console.log(
      `1. Your original component is now ${this.componentName}.v1${this.originalExtension}`,
    );
    console.log(`2. Add <UIFork /> to your app root (only in development):`);
    console.log(`
   <script setup>
   import { UIFork } from "uifork-vue"
   </script>

   <template>
     <YourApp />
     <UIFork v-if="isDev" />
   </template>
`);
    if (this.shouldWatch) {
      console.log("3. Starting watch mode...");
      console.log(
        `4. Add new versions by creating ${this.componentName}.v2${this.originalExtension}, ${this.componentName}.v1_1${this.originalExtension}, etc.`,
      );
      console.log(
        `5. Import the component: import ${this.componentName} from './${this.componentName}.vue'`,
      );
      // Start watching automatically
      new VersionSync(this.parentDir);
    } else {
      console.log(`3. Run: npx uifork-vue watch (to start the watch server)`);
      console.log(
        `4. Add new versions by creating ${this.componentName}.v2${this.originalExtension}, ${this.componentName}.v1_1${this.originalExtension}, etc.`,
      );
      console.log(
        `5. Import the component: import ${this.componentName} from './${this.componentName}.vue'`,
      );
    }
  }
}

module.exports = { UISwitcherScaffold };
